Registration page

<?php echo $this->my_name; ?>
<?php echo $this->form['open']; ?>
<?php echo $this->form['username_label']; ?>
<?php echo $this->form['username_input']; ?>
<?php echo $this->form['username_error']; ?>
<?php echo $this->form['first_name_label']; ?>
<?php echo $this->form['first_name_input']; ?>
<?php echo $this->form['first_name_error']; ?>
<?php echo $this->form['last_name_label']; ?>
<?php echo $this->form['last_name_input']; ?>
<?php echo $this->form['last_name_error']; ?>
<?php echo $this->form['email_label']; ?>
<?php echo $this->form['email_input']; ?>
<?php echo $this->form['email_error']; ?>
<?php echo $this->form['password_label']; ?>
<?php echo $this->form['password_input']; ?>
<?php echo $this->form['password_error']; ?>
<?php echo $this->form['repassword_label']; ?>
<?php echo $this->form['repassword_input']; ?>
<?php echo $this->form['agrrement_label']; ?>
<?php echo $this->form['agrrement_checkbox']; ?>
<?php echo $this->form['agrrement_error']; ?>

<?php echo $this->form['_token']; ?>
<?php echo $this->form['save_submit']; ?>
<?php echo $this->form['close']; ?> 

