<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <?= $this->meta_tags; ?>
        <?php
        OppCoreClasses\View\LayoutAppender::appendFooterJs([
            '/_templates/admin/plugins/jQuery/jQuery-2.1.4.min.js',
            '/_templates/admin/plugins/select2/select2.full.min.js',
            '/_templates/admin/plugins/datatables/jquery.dataTables.min.js',
            '/_templates/admin/plugins/datatables/dataTables.bootstrap.min.js',
            '/_templates/admin/plugins/slimScroll/jquery.slimscroll.min.js',
            '/_templates/admin/plugins/fastclick/fastclick.min.js',
            '/_templates/admin/plugins/jQueryUI/jquery-ui.js',
            '/_templates/admin/bootstrap/js/bootstrap.min.js',
            '/_templates/admin/dist/js/app.min.js',
            '/_templates/admin/dist/js/demo.js',
            '/_templates/plugins/tinymce/tinymce.min.js',
        ]);

        OppCoreClasses\View\LayoutAppender::appendHeadCss([
            '/_templates/admin/plugins/datatables/dataTables.bootstrap.css',
            '/_templates/admin/plugins/select2/select2.min.css',
            '/_templates/admin/bootstrap/css/bootstrap.min.css',
            '/_templates/font-awesome-4.6.3/css/font-awesome.min.css',
            '/_templates/common/ionicons.min.css',
            '/_templates/admin/dist/css/AdminLTE.min.css',
            '/_templates/admin/template.css',
            '/_templates/admin/dist/css/skins/_all-skins.min.css',
        ]);
        ?>
        <?= OppCoreClasses\View\LayoutAppender::generateAppendedHeadCss(); ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition skin-green sidebar-mini">
        <div id="system-notification"></div>
        <div id="dialog-overlay"></div>
        <div class="window-dialog_box">
            <div id="dialog"></div>
        </div>
        <div class="wrapper">
            <header class="main-header">
                <a href="/" class="logo">
                    <span class="logo-mini"><b>O</b>pp</span>
                    <span class="logo-lg"><b>Opp</b> CMS</span>
                </a>
                <nav class="navbar navbar-static-top" role="navigation">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <?= $this->top ?>
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <aside class="main-sidebar">
                <section class="sidebar">
                    <?= $this->left_sidabar; ?>
                </section>
            </aside>
            <div class="content-wrapper">
                <?= $this->content; ?>
                <?= $this->debug; ?>
            </div><!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    Anything you want
                </div>
                <strong>Copyright &copy; <?= date('Y'); ?>.</strong> All reight reserved!
            </footer>
            <aside class="control-sidebar control-sidebar-dark">
                <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                    <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
                    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="control-sidebar-home-tab">
                        <h3 class="control-sidebar-heading">Recent Activity</h3>
                        <ul class="control-sidebar-menu">
                            <li>
                                <a href="javascript::;">
                                    <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                                    <div class="menu-info">
                                        <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                                        <p>Will be 23 on April 24th</p>
                                    </div>
                                </a>
                            </li>
                        </ul><!-- /.control-sidebar-menu -->
                        <h3 class="control-sidebar-heading">Tasks Progress</h3>
                        <ul class="control-sidebar-menu">
                            <li>
                                <a href="javascript::;">
                                    <h4 class="control-sidebar-subheading">
                                        Custom Template Design
                                        <span class="label label-danger pull-right">70%</span>
                                    </h4>
                                    <div class="progress progress-xxs">
                                        <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                                    </div>
                                </a>
                            </li>
                        </ul><!-- /.control-sidebar-menu -->
                    </div><!-- /.tab-pane -->
                    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
                    <div class="tab-pane" id="control-sidebar-settings-tab">
                        <form method="post">
                            <h3 class="control-sidebar-heading">General Settings</h3>
                            <div class="form-group">
                                <label class="control-sidebar-subheading">
                                    Report panel usage
                                    <input type="checkbox" class="pull-right" checked>
                                </label>
                                <p>
                                    Some information about this general settings option
                                </p>
                            </div><!-- /.form-group -->
                        </form>
                    </div><!-- /.tab-pane -->
                </div>
            </aside><!-- /.control-sidebar -->
            <div class="control-sidebar-bg"></div>
        </div><!-- ./wrapper -->
        <?= OppCoreClasses\View\LayoutAppender::appendInlineFooterJs(ROOT_DIR . '/modules/Backend/System/Assets/js/initAdmin.js'); ?>
        <?= OppCoreClasses\View\LayoutAppender::generateAppendedFooterJs(); ?>
    </body>
</html>