<!-- User Account Menu -->
<!-- User Account: style can be found in dropdown.less -->
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="/_templates/admin/images/default_user_logo.png" class="user-image" alt="User Image">
        <span class="hidden-xs"><?= $this->username; ?></span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
            <img src="/_templates/admin/images/default_user_logo.png" class="img-circle" alt="User Image">
            <p>
                <?= $this->username; ?>
<!--                <small>Member since Nov. 2012</small>-->
            </p>
        </li>
        <!-- Menu Body -->
<!--        <li class="user-body">
            <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
            </div>
        </li>-->
        <!-- Menu Footer-->
        <li class="user-footer">
<!--            <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
            </div>-->
            <div class="pull-right">
                <a href="<?= $this->logout_url; ?>" class="btn btn-default btn-flat">Logout</a>
            </div>
        </li>
    </ul>
</li>