Debug urls: </br>
<?php
$debug = OppCoreClasses\Helper::getURL(['debug']);
$routes = OppCoreClasses\Helper::getURL(['debug','routes']);
echo $this->langCode;
echo '</br>';
echo '<a href="'.$debug.'">'.$debug .'</a>';
echo '</br>';
echo '<a href="'.$routes.'">'.$routes .'</a>';
echo '</br>';
echo '<a href="'.$debug.'">'.$debug .'</a>';
echo '</br>';
echo '<a href="'.$debug.'">'.$debug .'</a>';
echo '</br>';
echo '<a href="'.$debug.'">'.$debug .'</a>';
