<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= $this->title ?> - Admin</title>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <link rel="stylesheet" href="/_templates//admin/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="/_templates/admin/dist/css/AdminLTE.min.css">
        <link rel="stylesheet" href="/_templates/admin/plugins/iCheck/square/blue.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
            <div class="login-logo">
                <b><?= $this->title; ?></b> - Admin
            </div><!-- /.login-logo -->
            <div class="login-box-body">
                <p class="login-box-msg">Bejelentkezés az adminisztációs felületre</p>
                <?php echo $this->form['open']; ?>
                    <?php if($this->error_message != null){ ?>
                        <div class="alert alert-warning"><?php echo $this->error_message; ?></div>
                    <?php } ?>
                    <div class="form-group has-feedback">
                        <?php echo $this->form['email_input']; ?>
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                        <?php echo $this->form['email_error']; ?>
                    </div>
                    <div class="form-group has-feedback">
                        <?php echo $this->form['password_input']; ?>
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                        <?php echo $this->form['password_error']; ?>
                    </div>
                    <div class="row">
                        <div class="col-xs-8">
                            <?php
                            //<div class="checkbox icheck">
                            //    <label>
                            //        <input type="checkbox"> Bejelentkezve maradok
                            //    </label>
                            //</div>?>
                        </div><!-- /.col -->
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Belépés</button>
                        </div><!-- /.col -->
                    </div>
                <?php echo $this->form['close']; ?>

<?php
//         <a href="#">Elfelejtettem a jelszavam</a><br>
?>
            </div><!-- /.login-box-body -->
        </div><!-- /.login-box -->
<?php
//        <script src="/_templates/admin/plugins/jQuery/jQuery-2.1.4.min.js"></script>
//        <script src="/_templates/admin/bootstrap/js/bootstrap.min.js"></script>
//        <script src="/_templates/admin/plugins/iCheck/icheck.min.js"></script>
//        <script>
//            $(function () {
//                $('input').iCheck({
//                    checkboxClass: 'icheckbox_square-blue',
//                    radioClass: 'iradio_square-blue',
//                    increaseArea: '20%' // optional
//                });
//            });
//        </script>
?> 
    </body>
</html>