<?php //var_dump($this->data); ?>
<?php
use OppCoreClasses\View\LayoutAppender;

LayoutAppender::appendInlineFooterJs(__DIR__ . '/../../../Assets/js/categories.js');
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Contents
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <a href="<?= $this->create_link; ?>" class="btn btn-success">Add</a>
            <div class="box">
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Created by</th>
                                <th>Modified by</th>
                                <th>Status</th>
                                <th>Operations</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->data as $content): ?>
                                <tr>
                                    <td><?= $content->id ?></td>
                                    <td><?= $content->title ?></td>
                                    <td>
                                        <p><?= $content->c_last_name . ' ' . $content->c_first_name; ?></p>
                                        <p><?= date("m/d/Y h:i:s",$content->created_date    ); ?></p>
                                    </td>
                                    <td>
                                        <p><?= $content->m_last_name . ' ' . $content->m_first_name; ?></p>
                                        <p><?= ($content->modified_date ? date("m/d/Y h:i:s",$content->modified_date) : '' ); ?></p>
                                    </td>
                                    <td><?= ($content->active ? 'Publikus' : 'Rejtett') ?></td>
                                    <td>
                                        <a href="<?= $this->edit_link.'/'.$content->id ?>" class="btn-primary btn-sm"> <i class="fa fa-pencil"></i> </a>&nbsp;
                                        <a href="<?= $this->delete_link.$content->id ?>" class="btn-danger btn-sm delete"> <i class="fa fa-trash-o"></i> </a>&nbsp;
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Created by</th>
                                <th>Modified by</th>
                                <th>Status</th>
                                <th>Operations</th>
                            </tr>
                        </tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</section><!-- /.content -->
