<?php
use OppCoreClasses\View\LayoutAppender;

//echo $this->name;
//var_dump($this->languages);
//var_dump($this->form);
//CK Editor
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Edit content
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">User profile</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-12">
            <div class="nav-tabs-custom system-multi-language-tab">
                <ul class="nav nav-tabs">
                    <?php $first = true; ?>
                    <?php foreach ($this->languages as $language): ?>
                        <li class="<?= ($first ? "active" : "" ) ?>">
                            <a href="#lang_<?= $language->lang_code; ?>" data-toggle="tab">
                                <?= $language->lang_name; ?>
                            </a>
                        </li>
                        <?php $first = false; ?>
                    <?php endforeach; ?>
                </ul>
                <?php echo $this->form['open'] ?>
                <div class="tab-content">
                    <?php $first = true; ?>
                    <?php foreach ($this->languages as $language): ?>
                        <div class="<?= ($first ? "active" : "" ) ?> tab-pane" id="lang_<?= $language->lang_code; ?>">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <?php echo $this->form[$language->lang_code . '_title_label'] ?>
                                    <div class="col-sm-8">
                                        <?php echo $this->form[$language->lang_code . '_title_input'] ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->form[$language->lang_code . '_sef_label'] ?>
                                    <div class="col-sm-8">
                                        <?php echo $this->form[$language->lang_code . '_sef_input'] ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->form[$language->lang_code . '_keywords_label'] ?>
                                    <div class="col-sm-8">
                                        <?php echo $this->form[$language->lang_code . '_keywords_input'] ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->form[$language->lang_code . '_lead_label'] ?>
                                    <div class="col-sm-8">
                                        <?php echo $this->form[$language->lang_code . '_lead_input'] ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->form[$language->lang_code . '_text_label'] ?>
                                    <div class="col-sm-12">
                                        <?php echo $this->form[$language->lang_code . '_text_input'] ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->form[$language->lang_code . '_lang_id_label'] ?>
                                    <div class="col-sm-8">
                                        <?php echo $this->form[$language->lang_code . '_lang_id_input'] ?>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.tab-pane -->
                        <?php $first = false; ?>
                    <?php endforeach; ?>
                </div><!-- /.tab-content -->
                <div class="form-horizontal">
                    <div class="form-group">
                        <?php echo $this->form['_token'] ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->form['lead_image_label'] ?>
                        <div class="col-sm-8">
                            <?php echo $this->form['lead_image_input'] ?>
                            <?php echo $this->form['id_input'] ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->form['categories_label'] ?>
                        <div class="col-sm-8">
                            <div class="checkbox">
                                <?= $this->form['categories_selectlist'] ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->form['active_label'] ?>
                        <div class="col-sm-8">
                            <div class="checkbox">
                                <?php echo $this->form['active_radio'] ?>           
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-8">
                            <?php echo $this->form['save_submit'] ?>
                        </div>
                    </div>
                    <?php echo $this->form['close'] ?>
                </div>
            </div><!-- /.nav-tabs-custom -->
        </div><!-- /.col -->
    </div><!-- /.row -->
    <div class="row">
        <div class="col-md-4">
            <!-- Help Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Breaf</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Kategória neve</strong>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Szülő kategória</strong>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
        <div class="col-md-4">
            <!-- Help Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ismertető</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Kategória neve</strong>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Szülő kategória</strong>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
        <div class="col-md-4">
            <!-- Help Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ismertető</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Kategória neve</strong>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Szülő kategória</strong>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div>
</section><!-- /.content -->


<?php 
$inlineScript = '
$(function () {
        //Initialize Select2 Elements
        $(".select2").select2();
})';
foreach ($this->languages as $language){
    $inlineScript .= "
      $(function () {
        CKEDITOR.replace('". $language->lang_code ."_text');
      });";
} 
LayoutAppender::appendInlineScriptFooterJs($inlineScript);

?>
